name: Continuous Deployment Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Build Image & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dataloplatforms/signature-app:latest
            dataloplatforms/signature-app:${{ github.sha }} 
