name: Continuous Deployment Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Build Image & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug - verificar secret
        run: |
          if [ -z "${{ secrets.BACKEND_API_URL }}" ]; then
            echo "BACKEND_API_URL está vacío o no existe como secret"
          else
            echo "BACKEND_API_URL tiene un valor definido"
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: false
          build-args: |
            BACKEND_API_URL=${{ secrets.BACKEND_API_URL }}
          tags: |
            dataloplatforms/signature-app:latest
            dataloplatforms/signature-app:${{ github.sha }}

      - name: Actualizar contenedor en el Servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: |
            echo "Enviando solicitud de despliegue a Dokploy..."
            RESPONSE=$(curl -s -X POST "https://dokploy.data-lo.online/api/deploy/compose/LfalPhwe9vfvstQuQ8y5n")
            echo "Respuesta del servidor: $RESPONSE"
            echo "¡Despliegue solicitado con éxito!"

