name: Continuos Integration Development

on:
    push:
        branches:
            - development
    pull_request:
        branches:
            - development

jobs:
    build:
        name: Build & Compile (Node.js)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del código
              uses: actions/checkout@v4
            
            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '22'
                cache: 'npm' 

            - name: Instalar dependencias
              run: npm ci

            - name: Compilación de Node.js
              run: npm run build
            
